import React, { useState } from 'react';
import { ArrowLeft, Building2, LockKeyhole, ShieldCheck } from 'lucide-react';
import { getMe, login } from '../api';

type Props = { onAuthenticated: (user: any) => void; initialView?: 'LOGIN' | 'REQUEST_ACCESS'; onBack?: () => void };

export const Auth = ({ onAuthenticated, initialView = 'LOGIN', onBack }: Props) => {
  const [view, setView] = useState(initialView);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const handleSubmit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await login(email, password); const session = await getMe(); const membership = session.membership; if (!membership) throw new Error('Your account has no active organization membership.'); onAuthenticated({ id: session.user.id, name: session.user.full_name, email: session.user.email, organization: membership.organization.name, organizationId: membership.organization.id, department: membership.department?.name || '—', departmentId: membership.department?.id, role: membership.role, membership }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to sign in.'); } finally { setBusy(false); } };
  return <div className="min-h-screen bg-slate-50 flex items-center justify-center p-5"><div className="w-full max-w-md"><button onClick={onBack} className="text-sm text-slate-500 hover:text-slate-900 mb-6"><ArrowLeft className="inline mr-2" size={15} />Back</button>{view === 'REQUEST_ACCESS' ? <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-7"><div className="w-10 h-10 rounded-lg bg-blue-50 text-blue-700 flex items-center justify-center mb-5"><Building2 size={20} /></div><h1 className="text-2xl font-semibold tracking-tight">Request professional access</h1><p className="text-sm text-slate-600 leading-relaxed mt-3">Access is managed by each healthcare organization. Contact your hospital administrator to be invited and assigned to the appropriate department.</p><div className="mt-6 p-4 rounded-xl bg-slate-50 border border-slate-100 text-sm text-slate-600"><ShieldCheck className="inline mr-2 text-emerald-600" size={16} />Only active organization memberships can open patient records.</div><button onClick={() => setView('LOGIN')} className="mt-6 w-full bg-slate-900 text-white rounded-lg py-3 text-sm font-semibold hover:bg-slate-700">Return to sign in</button></div> : <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-7"><div className="flex items-center gap-3 mb-8"><div className="w-9 h-9 rounded-lg bg-slate-900 text-white flex items-center justify-center font-bold">G</div><div><div className="font-semibold">GenomixAI</div><div className="text-xs text-slate-500">Professional clinical workspace</div></div></div><h1 className="text-2xl font-semibold tracking-tight">Sign in</h1><p className="text-sm text-slate-500 mt-2 mb-7">Use your professional account. Access is based on your organization membership.</p><form onSubmit={handleSubmit} className="space-y-4"><label className="field-label">Email<input className="field-input" type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="name@hospital.org" /></label><label className="field-label">Password<div className="relative"><LockKeyhole className="absolute left-3 top-3 text-slate-400" size={15} /><input className="field-input pl-9" type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" /></div></label>{error && <div className="rounded-lg bg-red-50 border border-red-100 p-3 text-sm text-red-700">{error}</div>}<button disabled={busy} className="w-full bg-slate-900 text-white rounded-lg py-3 text-sm font-semibold hover:bg-slate-700 disabled:opacity-60">{busy ? 'Signing in…' : 'Sign in'}</button></form><button onClick={() => setView('REQUEST_ACCESS')} className="w-full mt-5 text-sm font-semibold text-blue-700 hover:text-blue-900">Need professional access?</button></div>}<p className="text-center text-xs text-slate-400 mt-5">Authorized healthcare use only</p></div></div>;
};
