import React from 'react';
import { ArrowRight, Building2, CheckCircle2, ClipboardCheck, Dna, ShieldCheck } from 'lucide-react';

export const LandingPage: React.FC<{ onSignIn: () => void; onRequestAccess: () => void }> = ({ onSignIn, onRequestAccess }) => (
  <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-200 bg-white">
      <div className="max-w-7xl mx-auto px-5 md:px-8 h-16 flex items-center justify-between">
        <div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-slate-900 text-white flex items-center justify-center font-bold">G</div><span className="font-semibold tracking-tight">GenomixAI</span></div>
        <div className="flex items-center gap-3"><button onClick={onSignIn} className="text-sm font-semibold text-slate-700 px-4 py-2 hover:text-slate-950">Sign in</button><button onClick={onRequestAccess} className="text-sm font-semibold text-white bg-slate-900 rounded-lg px-4 py-2.5 hover:bg-slate-700">Request access</button></div>
      </div>
    </header>
    <main>
      <section className="max-w-7xl mx-auto px-5 md:px-8 py-20 md:py-28 grid lg:grid-cols-2 gap-16 items-center">
        <div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-700 mb-5">Clinical medication review</p><h1 className="text-4xl md:text-6xl font-semibold tracking-tight leading-[1.08] text-slate-950">Clearer medication decisions for clinical teams.</h1><p className="text-lg text-slate-600 leading-relaxed mt-6 max-w-xl">GenomixAI brings patient history, pharmacogenomic results, and evidence into one review workflow for healthcare organizations.</p><div className="flex flex-wrap gap-3 mt-8"><button onClick={onSignIn} className="inline-flex items-center gap-2 bg-slate-900 text-white px-5 py-3 rounded-lg text-sm font-semibold hover:bg-slate-700">Open clinical workspace <ArrowRight size={16} /></button><button onClick={onRequestAccess} className="inline-flex items-center gap-2 border border-slate-300 bg-white text-slate-700 px-5 py-3 rounded-lg text-sm font-semibold hover:bg-slate-50">Request professional access</button></div></div>
        <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-6 md:p-8"><div className="flex items-center justify-between border-b border-slate-100 pb-5"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Workspace overview</p><p className="font-semibold mt-1">A structured clinical review</p></div><ShieldCheck className="text-blue-700" size={24} /></div><div className="space-y-4 py-6"><div className="flex gap-4 items-start"><div className="w-9 h-9 rounded-lg bg-blue-50 text-blue-700 flex items-center justify-center shrink-0"><Dna size={18} /></div><div><p className="font-semibold text-sm">Patient context</p><p className="text-sm text-slate-500 mt-1">Review authorized clinical and pharmacogenomic records together.</p></div></div><div className="flex gap-4 items-start"><div className="w-9 h-9 rounded-lg bg-emerald-50 text-emerald-700 flex items-center justify-center shrink-0"><ClipboardCheck size={18} /></div><div><p className="font-semibold text-sm">Structured assessment</p><p className="text-sm text-slate-500 mt-1">Keep findings, evidence, pharmacist review, and decisions traceable.</p></div></div><div className="flex gap-4 items-start"><div className="w-9 h-9 rounded-lg bg-slate-100 text-slate-700 flex items-center justify-center shrink-0"><Building2 size={18} /></div><div><p className="font-semibold text-sm">Organization workspace</p><p className="text-sm text-slate-500 mt-1">Access is controlled by your organization membership and role.</p></div></div></div><div className="border-t border-slate-100 pt-5 text-xs text-slate-400 flex items-center gap-2"><CheckCircle2 size={14} className="text-emerald-600" /> Built for professional clinical review</div></div>
      </section>
      <section className="border-y border-slate-200 bg-white"><div className="max-w-7xl mx-auto px-5 md:px-8 py-16 grid md:grid-cols-3 gap-8"><div><h2 className="text-xl font-semibold">One place for the record</h2><p className="text-sm text-slate-500 leading-relaxed mt-3">Patient identity, history, medications, labs, vitals, allergies, and genomic profiles remain connected to the chart.</p></div><div><h2 className="text-xl font-semibold">Evidence stays visible</h2><p className="text-sm text-slate-500 leading-relaxed mt-3">Clinical findings can be reviewed alongside their source and provenance.</p></div><div><h2 className="text-xl font-semibold">People stay in control</h2><p className="text-sm text-slate-500 leading-relaxed mt-3">The platform supports physician and pharmacist collaboration. It does not replace clinical judgment.</p></div></div></section>
      <section className="max-w-3xl mx-auto px-5 md:px-8 py-20 text-center"><h2 className="text-3xl font-semibold tracking-tight">A focused workspace for medication review.</h2><p className="text-slate-600 mt-4">Sign in with your professional account to access your organization’s authorized records.</p><button onClick={onSignIn} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-blue-700 hover:text-blue-900">Sign in to continue <ArrowRight size={16} /></button></section>
    </main>
    <footer className="border-t border-slate-200 bg-white"><div className="max-w-7xl mx-auto px-5 md:px-8 py-6 flex flex-col sm:flex-row gap-2 justify-between text-xs text-slate-400"><span>GenomixAI clinical workspace</span><span>For authorized healthcare professionals</span></div></footer>
  </div>
);
