import React, { useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, FileText, Loader2, Pill, Send, ShieldAlert } from 'lucide-react';
import { analyzeAssessment, createAssessment, createReport, recordDecision, requestReview } from '../api';
import { DrugInfo, Patient } from '../types';

export const MedicationAssessment = ({ patient, drug, initialDose, initialFrequency, onBack, onComplete }: { patient: Patient; drug: DrugInfo; initialDose: number; initialFrequency: string; onBack: () => void; onComplete: () => void }) => {
  const [assessment, setAssessment] = useState<any>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const runAnalysis = async () => {
    if (!patient.organizationId) return;
    setBusy(true); setError('');
    try { const draft = await createAssessment(patient.id, patient.organizationId, [{ medication_id: drug.id, dose: initialDose, dose_unit: 'mg', route: 'ORAL', frequency: initialFrequency, source: 'FRONTEND' }]); setAssessment(await analyzeAssessment(draft.id, patient.organizationId)); }
    catch (e) { setError(e instanceof Error ? e.message : 'Unable to analyze assessment.'); } finally { setBusy(false); }
  };
  const sendToPharmacist = async () => { if (!assessment || !patient.organizationId) return; setBusy(true); try { setAssessment(await requestReview(assessment.id, patient.organizationId, message)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to request review.'); } finally { setBusy(false); } };
  const exportReport = async () => { if (!assessment || !patient.organizationId) return; setBusy(true); try { const report = await createReport(assessment.id, patient.organizationId); const apiBase = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1').replace(/\/$/, ''); window.open(`${apiBase}${report.download_path.replace('/api/v1', '')}`, '_blank'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to generate report.'); } finally { setBusy(false); } };
  const finalize = async () => { if (!assessment || !patient.organizationId) return; setBusy(true); try { await recordDecision(assessment.id, patient.organizationId, { decision: 'ACCEPT', decision_rationale: 'Physician accepted the analyzed proposal.', medications: [{ medication_id: drug.id, dose: initialDose, dose_unit: 'mg', route: 'ORAL', frequency: initialFrequency, start_date: new Date().toISOString().slice(0, 10) }], finalize: true }); onComplete(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to record final decision.'); } finally { setBusy(false); } };
  const findings = assessment?.findings || [];
  return <div className="h-full overflow-y-auto bg-hospital-bg"><div className="max-w-5xl mx-auto p-6 space-y-6"><button onClick={onBack} className="text-sm text-hospital-blue"><ArrowLeft className="inline mr-2" size={16} /> Back to patient chart</button><div className="bg-white border border-hospital-border rounded-xl shadow-sm p-6"><div className="flex items-center gap-3"><Pill className="text-hospital-blue" /><div><h1 className="text-2xl font-bold text-slate-900">Medication Assessment</h1><p className="text-sm text-slate-500">{patient.name} · {patient.mrn}</p></div></div><div className="mt-6 p-4 bg-blue-50 border border-blue-100 rounded-lg"><div className="font-bold text-hospital-blue">{drug.name}</div><div className="text-sm text-slate-600">{initialDose} mg · {initialFrequency} · ORAL</div></div></div>
    {error && <div className="p-4 rounded-lg bg-red-50 border border-red-200 text-sm text-red-700"><AlertTriangle className="inline mr-2" size={16} />{error}</div>}
    {!assessment ? <div className="bg-white border border-hospital-border rounded-xl shadow-sm p-6"><p className="text-sm text-slate-600 mb-5">Review the patient's record against the selected medication and see the supporting evidence.</p><button onClick={runAnalysis} disabled={busy} className="bg-hospital-blue text-white px-5 py-3 rounded-lg font-bold text-sm">{busy ? <><Loader2 className="inline animate-spin mr-2" size={16} />Analyzing…</> : <><ShieldAlert className="inline mr-2" size={16} />Run clinical assessment</>}</button></div> : <><div className="bg-white border border-hospital-border rounded-xl shadow-sm p-6"><div className="flex justify-between items-center mb-5"><h2 className="font-bold text-slate-900">Structured findings</h2><span className="text-xs font-bold uppercase text-hospital-blue">{assessment.status}</span></div>{findings.length === 0 ? <p className="text-sm text-slate-500">No actionable findings were returned.</p> : <div className="space-y-3">{findings.map((finding: any) => <div key={finding.id} className="p-4 border rounded-lg"><div className="flex gap-2 items-center font-bold text-sm"><AlertTriangle size={16} className="text-amber-600" />{finding.category} · {finding.severity}</div><p className="text-sm text-slate-700 mt-2">{finding.summary}</p><p className="text-xs text-slate-500 mt-1">{finding.details}</p></div>)}</div>}</div><div className="bg-white border border-hospital-border rounded-xl shadow-sm p-6 space-y-4"><h2 className="font-bold text-slate-900">Clinical workflow</h2><textarea value={message} onChange={e => setMessage(e.target.value)} className="w-full border rounded-lg p-3 text-sm" placeholder="Optional message for the clinical pharmacist" /><div className="flex flex-wrap gap-3"><button onClick={sendToPharmacist} disabled={busy || assessment.status !== 'ANALYZED'} className="bg-hospital-blue text-white px-4 py-2.5 rounded-lg font-bold text-sm"><Send className="inline mr-2" size={15} />Request pharmacist review</button><button onClick={finalize} disabled={busy || !['ANALYZED', 'PHARMACIST_RECOMMENDED', 'RETURNED_TO_PHYSICIAN'].includes(assessment.status)} className="bg-emerald-600 text-white px-4 py-2.5 rounded-lg font-bold text-sm"><CheckCircle2 className="inline mr-2" size={15} />Finalize decision</button><button onClick={exportReport} disabled={busy} className="border border-slate-300 px-4 py-2.5 rounded-lg font-bold text-sm"><FileText className="inline mr-2" size={15} />Generate report</button></div></div></>}
  </div></div>;
};
