import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowLeft, Bell, Building, ChevronRight, ClipboardList, FileText, FlaskConical, History, Loader2, Pill, Search, User, X, Zap } from 'lucide-react';
import { getMe, getPatientBundle, getToken, listMedications, listNotifications, listPatients, logout, readNotification } from './api';
import { Auth } from './components/Auth';
import { LandingPage } from './components/LandingPage';
import { MedicationAssessment } from './components/MedicationAssessment';
import { PharmacistWorkspace } from './components/PharmacistWorkspace';
import { DrugInfo, Patient } from './types';

type Screen = 'SEARCH' | 'RETRIEVAL' | 'CHART' | 'ASSESSMENT';
type AppState = 'LANDING' | 'UNAUTHENTICATED' | 'AUTHENTICATED';
type SessionUser = { id: string; name: string; email: string; organization: string; organizationId: string; department: string; departmentId?: string; role: string };

function mapPatient(item: Record<string, any>): Patient {
  const birthDate = new Date(item.date_of_birth);
  const today = new Date();
  const age = today.getFullYear() - birthDate.getFullYear() - ((today.getMonth() < birthDate.getMonth() || (today.getMonth() === birthDate.getMonth() && today.getDate() < birthDate.getDate())) ? 1 : 0);
  return { id: item.id, name: `${item.first_name} ${item.last_name}`, age, sex: item.sex === 'MALE' ? 'M' : 'F', mrn: item.mrn, lastVisit: '—', status: item.status === 'ACTIVE' ? 'Active' : 'Inactive', conditions: [], medications: [], allergies: [], labs: [], organizationId: item.organization_id };
}

function mapBundle(base: Patient, bundle: any): Patient {
  return { ...base, lastVisit: bundle.timeline[0]?.timestamp ? new Date(bundle.timeline[0].timestamp).toLocaleDateString() : '—', conditions: bundle.conditions.map((item: any) => item.name), allergies: bundle.allergies.map((item: any) => item.allergen), medications: bundle.medications.map((item: any) => ({ id: item.id, name: item.medication.generic_name, dose: `${item.dose} ${item.dose_unit}`, frequency: item.frequency, route: item.route, startDate: item.start_date, status: item.status === 'ACTIVE' ? 'Active' : 'Discontinued' })), labs: bundle.labs.map((item: any) => ({ name: item.test_name, value: String(item.value), unit: item.unit, date: item.collected_at, status: 'Normal' })), clinicalNotes: bundle.notes.map((item: any) => item.content).join('\n'), genomicProfile: bundle.genomics[0] ? { variants: bundle.genomics.flatMap((profile: any) => profile.variants.map((variant: any) => ({ gene: variant.gene, variant: variant.variant, phenotype: variant.phenotype || 'Not interpreted' }))) } : undefined };
}

function Header({ user, onSignOut }: { user: SessionUser; onSignOut: () => void }) {
  const [open, setOpen] = useState(false);
  const [profile, setProfile] = useState(false);
  const [notifications, setNotifications] = useState<any[]>([]);
  useEffect(() => { listNotifications(user.organizationId).then(setNotifications).catch(() => setNotifications([])); }, [user.organizationId]);
  return <header className="h-14 shrink-0 border-b border-slate-200 bg-white flex items-center justify-between px-5 sticky top-0 z-50"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-slate-900 text-white flex items-center justify-center font-bold">G</div><span className="font-semibold tracking-tight text-slate-900">GenomixAI</span><span className="hidden md:inline text-xs text-slate-400 border-l border-slate-200 pl-3">Clinical workspace</span></div><div className="flex items-center gap-4"><div className="relative"><button aria-label="Notifications" onClick={() => setOpen(!open)} className="relative p-2 text-slate-500 hover:text-slate-900 rounded-lg hover:bg-slate-50"><Bell size={18} />{notifications.some(item => !item.is_read) && <span className="absolute top-1 right-1 w-2 h-2 rounded-full bg-amber-500 border border-white" />}</button>{open && <div className="absolute right-0 mt-2 w-80 bg-white border border-slate-200 rounded-xl shadow-lg p-3"><div className="px-2 pb-2 text-[10px] font-bold uppercase tracking-widest text-slate-400">Workflow notifications</div>{notifications.length === 0 ? <p className="p-2 text-sm text-slate-500">No notifications.</p> : notifications.map(item => <button key={item.id} onClick={() => { if (!item.is_read) { readNotification(item.id, user.organizationId).catch(() => undefined); setNotifications(current => current.map(entry => entry.id === item.id ? { ...entry, is_read: true } : entry)); } }} className={`w-full text-left p-3 rounded-lg mb-1 ${item.is_read ? 'hover:bg-slate-50' : 'bg-blue-50'}`}><div className="text-sm font-semibold text-slate-800">{item.title}</div><div className="text-xs text-slate-500 mt-1">{item.message}</div></button>)}</div>}</div><div className="h-6 border-l border-slate-200" /><div className="relative"><button onClick={() => setProfile(!profile)} className="flex items-center gap-2"><div className="hidden sm:block text-right"><div className="text-xs font-semibold text-slate-800">{user.name}</div><div className="text-[11px] text-slate-500">{user.department}</div></div><div className="w-8 h-8 rounded-full bg-slate-100 border border-slate-200 flex items-center justify-center"><User size={16} className="text-slate-600" /></div></button>{profile && <div className="absolute right-0 mt-2 w-60 bg-white border border-slate-200 rounded-xl shadow-lg overflow-hidden"><div className="p-4 bg-slate-50 border-b border-slate-200"><div className="font-semibold text-sm">{user.name}</div><div className="text-xs text-slate-500 mt-1">{user.organization}</div><div className="text-xs text-slate-500">{user.role}</div></div><button onClick={onSignOut} className="w-full px-4 py-3 text-left text-sm text-red-600 hover:bg-red-50">Sign out</button></div>}</div></div></header>;
}

function Dashboard({ user, onSelect }: { user: SessionUser; onSelect: (patient: Patient) => void }) {
  const [query, setQuery] = useState('');
  const [patients, setPatients] = useState<Patient[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { setLoading(true); setError(''); listPatients(user.organizationId, query).then(result => setPatients(result.items.map(mapPatient))).catch(e => setError(e instanceof Error ? e.message : 'Unable to load patients.')).finally(() => setLoading(false)); }, [query, user.organizationId]);
  return <main className="max-w-7xl w-full mx-auto p-5 md:p-8"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 mb-8"><div><p className="text-xs uppercase tracking-widest font-bold text-slate-400 mb-2">{user.organization}</p><h1 className="text-2xl md:text-3xl font-semibold tracking-tight text-slate-900">Patient workspace</h1><p className="text-sm text-slate-500 mt-2">Find a patient by name, MRN, or GenomixAI ID.</p></div><div className="text-sm text-slate-500">{user.role.replaceAll('_', ' ')}</div></div><section className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-200"><div className="relative max-w-xl"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={query} onChange={e => setQuery(e.target.value)} autoFocus placeholder="Search patients" className="w-full h-12 pl-11 pr-4 rounded-xl border border-slate-200 bg-slate-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-400 text-sm" /></div></div>{loading ? <div className="p-16 text-center text-slate-500"><Loader2 className="inline animate-spin mr-2" size={18} />Loading patient records…</div> : error ? <div className="p-16 text-center text-red-600">{error}</div> : patients.length === 0 ? <div className="p-16 text-center"><User className="mx-auto text-slate-300 mb-3" size={30} /><p className="font-medium text-slate-700">No patient records found</p><p className="text-sm text-slate-500 mt-1">Try a different name, MRN, or patient ID.</p></div> : <div className="divide-y divide-slate-100">{patients.map(patient => <button key={patient.id} onClick={() => onSelect(patient)} className="w-full text-left px-5 py-4 flex items-center gap-4 hover:bg-slate-50 transition-colors"><div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center text-slate-600 font-semibold">{patient.name.split(' ').map(part => part[0]).join('').slice(0, 2)}</div><div className="flex-1"><div className="font-semibold text-slate-900">{patient.name}</div><div className="text-xs text-slate-500 mt-1">MRN {patient.mrn} · {patient.age}y · {patient.sex}</div></div><span className="text-xs text-slate-400">{patient.status}</span><ChevronRight size={18} className="text-slate-300" /></button>)}</div>}</section></main>;
}

function Retrieval({ patient, onComplete }: { patient: Patient; onComplete: () => void }) { useEffect(() => { const timer = window.setTimeout(onComplete, 250); return () => window.clearTimeout(timer); }, [onComplete]); return <div className="fixed inset-0 z-40 bg-slate-50 flex items-center justify-center"><div className="text-center"><Loader2 className="mx-auto text-blue-600 animate-spin" size={32} /><p className="mt-4 font-medium text-slate-800">Loading patient record</p><p className="mt-1 text-sm text-slate-500">Opening the records available to you for {patient.name}</p></div></div>; }

function recordLabel(item: any) {
  if (item.test_name) return `${item.test_name}: ${item.value ?? '—'} ${item.unit || ''}`;
  if (item.vital_type) return `${item.vital_type}: ${item.value ?? '—'} ${item.unit || ''}`;
  if (item.gene) return `${item.gene} · ${item.variant || 'Variant'} · ${item.phenotype || 'No interpretation'}`;
  if (item.encounter_type) return `${item.encounter_type}${item.reason ? ` · ${item.reason}` : ''}`;
  if (item.allergen) return `${item.allergen}${item.reaction ? ` · ${item.reaction}` : ''}`;
  if (item.medication) return typeof item.medication === 'string' ? item.medication : item.medication.generic_name;
  if (item.content) return item.content;
  return item.name || item.summary || 'Clinical record';
}

function DataList({ items, empty }: { items: any[]; empty: string }) { return items.length === 0 ? <p className="text-sm text-slate-500 py-6">{empty}</p> : <div className="space-y-2">{items.map((item, index) => <div key={item.id || index} className="p-3 rounded-lg bg-slate-50 border border-slate-100 text-sm">{recordLabel(item)}</div>)}</div>; }

function PatientChart({ patient, bundle, onBack, onAddMedication }: { patient: Patient; bundle: any; onBack: () => void; onAddMedication: () => void }) {
  const [tab, setTab] = useState('Overview');
  const tabs = [{ id: 'Overview', label: 'Overview', icon: FileText }, { id: 'History', label: 'History', icon: History }, { id: 'Vitals', label: 'Vitals', icon: Activity }, { id: 'Labs', label: 'Labs', icon: FlaskConical }, { id: 'Medications', label: 'Medications', icon: Pill }, { id: 'Allergies', label: 'Allergies', icon: AlertTriangle }, { id: 'Notes', label: 'Notes', icon: ClipboardList }, { id: 'Genomics', label: 'Genomics', icon: Zap }, { id: 'Timeline', label: 'Timeline', icon: History }];
  const content = tab === 'Overview' ? <div className="grid md:grid-cols-2 gap-5"><section className="panel"><h3>Active conditions</h3><DataList items={bundle.conditions} empty="No active conditions recorded." /></section><section className="panel"><h3>Active medications</h3><DataList items={bundle.medications.filter((item: any) => item.status === 'ACTIVE')} empty="No active medications recorded." /><button onClick={onAddMedication} className="mt-4 text-sm font-semibold text-blue-700">Add medication assessment <ChevronRight className="inline" size={15} /></button></section><section className="panel md:col-span-2"><h3>Recent clinical notes</h3><DataList items={bundle.notes.slice(0, 3)} empty="No clinical notes recorded." /></section></div> : tab === 'History' ? <section className="panel"><h3>Encounters and history</h3><DataList items={bundle.encounters} empty="No encounters recorded." /></section> : tab === 'Vitals' ? <section className="panel"><h3>Vitals</h3><DataList items={bundle.vitals} empty="No vitals recorded." /></section> : tab === 'Labs' ? <section className="panel"><h3>Laboratory results</h3><DataList items={bundle.labs} empty="No laboratory results recorded." /></section> : tab === 'Medications' ? <section className="panel"><div className="flex items-center justify-between"><h3>Medication history</h3><button onClick={onAddMedication} className="text-sm font-semibold text-blue-700">New assessment</button></div><DataList items={bundle.medications} empty="No medications recorded." /></section> : tab === 'Allergies' ? <section className="panel"><h3>Allergies and adverse reactions</h3><DataList items={[...bundle.allergies, ...bundle.adverseReactions]} empty="No allergies or adverse reactions recorded." /></section> : tab === 'Notes' ? <section className="panel"><h3>Physician notes</h3><DataList items={bundle.notes} empty="No physician notes recorded." /></section> : tab === 'Genomics' ? <section className="panel"><div className="flex justify-between items-center"><h3>Pharmacogenomic profile</h3>{bundle.genomics[0] && <span className="source-label">{bundle.genomics[0].source}</span>}</div><DataList items={bundle.genomics.flatMap((profile: any) => profile.variants)} empty="No pharmacogenomic profile recorded." /></section> : <section className="panel"><h3>Clinical timeline</h3><DataList items={bundle.timeline} empty="No clinical events recorded." /></section>;
  return <main className="max-w-7xl w-full mx-auto p-5 md:p-8"><button onClick={onBack} className="text-sm text-slate-500 hover:text-slate-900 mb-5"><ArrowLeft className="inline mr-2" size={15} />Back to patient search</button><div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-6"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold text-slate-900">{patient.name}</h1><span className="status-label">{patient.status}</span></div><p className="text-sm text-slate-500 mt-2">MRN {patient.mrn} · {patient.age} years · {patient.sex}</p></div><div className="text-xs text-slate-500 flex items-center gap-2"><Building size={14} /> {patient.organizationId}</div></div><div className="border-b border-slate-200 overflow-x-auto"><div className="flex gap-5 min-w-max">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`py-3 text-sm font-medium border-b-2 ${tab === id ? 'border-blue-600 text-blue-700' : 'border-transparent text-slate-500 hover:text-slate-800'}`}><Icon className="inline mr-2" size={15} />{label}</button>)}</div></div><div className="mt-6">{content}</div></main>;
}

export default function App() {
  const [appState, setAppState] = useState<AppState>('LANDING'); const [authView, setAuthView] = useState<'LOGIN' | 'REQUEST_ACCESS'>('LOGIN'); const [user, setUser] = useState<SessionUser | null>(null); const [screen, setScreen] = useState<Screen>('SEARCH'); const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null); const [bundle, setBundle] = useState<any>(null); const [selectedDrug, setSelectedDrug] = useState<DrugInfo | null>(null); const [dose, setDose] = useState(0); const [frequency, setFrequency] = useState('Once Daily'); const [adding, setAdding] = useState(false); const [drugs, setDrugs] = useState<DrugInfo[]>([]); const [notice, setNotice] = useState('');
  useEffect(() => { const handleUnauthorized = () => { setUser(null); setAppState('UNAUTHENTICATED'); setAuthView('LOGIN'); }; window.addEventListener('genomixai:unauthorized', handleUnauthorized); return () => window.removeEventListener('genomixai:unauthorized', handleUnauthorized); }, []);
  useEffect(() => { if (!getToken()) return; getMe().then(session => { const membership = session.membership; if (!membership) return; setUser({ id: session.user.id, name: session.user.full_name, email: session.user.email, organization: membership.organization.name, organizationId: membership.organization.id, department: membership.department?.name || '—', departmentId: membership.department?.id, role: membership.role }); setAppState('AUTHENTICATED'); }).catch(() => undefined); }, []);
  useEffect(() => { if (appState === 'AUTHENTICATED') listMedications().then(items => setDrugs(items.map(item => ({ id: item.id, name: item.generic_name, class: item.dosage_form || 'Medication', standardDose: item.strength || '', indications: [] })))).catch(() => setDrugs([])); }, [appState]);
  if (appState === 'LANDING') return <LandingPage onSignIn={() => { setAuthView('LOGIN'); setAppState('UNAUTHENTICATED'); }} onRequestAccess={() => { setAuthView('REQUEST_ACCESS'); setAppState('UNAUTHENTICATED'); }} />;
  if (appState === 'UNAUTHENTICATED') return <Auth initialView={authView} onBack={() => setAppState('LANDING')} onAuthenticated={session => { setUser(session); setAppState('AUTHENTICATED'); }} />;
  if (!user) return null;
  if (user.role === 'CLINICAL_PHARMACIST') return <div className="min-h-screen bg-slate-50 flex flex-col"><Header user={user} onSignOut={() => { logout().catch(() => undefined); setUser(null); setAppState('LANDING'); }} /><PharmacistWorkspace user={user} onSignOut={() => setAppState('LANDING')} /></div>;
  const selectPatient = async (patient: Patient) => { setSelectedPatient(patient); setScreen('RETRIEVAL'); if (patient.organizationId) { try { const data = await getPatientBundle(patient.id, patient.organizationId); setBundle(data); setSelectedPatient(mapBundle(patient, data)); } catch { setBundle(null); setNotice('Unable to load this patient record.'); setScreen('SEARCH'); window.setTimeout(() => setNotice(''), 4000); } } };
  const startAssessment = (drug: DrugInfo, selectedDose: number, selectedFrequency: string) => { setSelectedDrug(drug); setDose(selectedDose); setFrequency(selectedFrequency); setAdding(false); setScreen('ASSESSMENT'); };
  return <div className="min-h-screen bg-slate-50 flex flex-col"><Header user={user} onSignOut={() => { logout().catch(() => undefined); setUser(null); setAppState('LANDING'); }} /><div className="flex-1">{screen === 'SEARCH' && <Dashboard user={user} onSelect={selectPatient} />}{screen === 'RETRIEVAL' && selectedPatient && <Retrieval patient={selectedPatient} onComplete={() => setScreen('CHART')} />}{screen === 'CHART' && selectedPatient && bundle && <PatientChart patient={selectedPatient} bundle={bundle} onBack={() => setScreen('SEARCH')} onAddMedication={() => setAdding(true)} />}{screen === 'ASSESSMENT' && selectedPatient && selectedDrug && <MedicationAssessment patient={selectedPatient} drug={selectedDrug} initialDose={dose} initialFrequency={frequency} onBack={() => setScreen('CHART')} onComplete={() => { setNotice('Final decision recorded.'); setScreen('CHART'); window.setTimeout(() => setNotice(''), 4000); }} />}</div>{notice && <div className="fixed bottom-5 right-5 bg-slate-900 text-white rounded-xl px-4 py-3 text-sm shadow-lg">{notice}</div>}{adding && <div className="fixed inset-0 z-50 bg-slate-900/30 flex items-center justify-center p-4"><form onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); const drug = drugs.find(item => item.name.toLowerCase() === String(form.get('drug')).toLowerCase()); if (drug) startAssessment(drug, Number(form.get('dose')), String(form.get('frequency'))); }} className="bg-white rounded-2xl shadow-xl border border-slate-200 w-full max-w-md p-6"><div className="flex items-center justify-between mb-6"><div><h2 className="font-semibold text-slate-900">New medication assessment</h2><p className="text-xs text-slate-500 mt-1">Choose a medication to review.</p></div><button type="button" onClick={() => setAdding(false)}><X size={18} className="text-slate-400" /></button></div><label className="field-label">Medication<select name="drug" required className="field-input"><option value="">Select medication</option>{drugs.map(drug => <option key={drug.id}>{drug.name}</option>)}</select></label><label className="field-label">Dose<input name="dose" type="number" min="0.01" step="any" required className="field-input" placeholder="Dose" /></label><label className="field-label">Frequency<select name="frequency" className="field-input"><option>Once Daily</option><option>Twice Daily</option><option>Three times Daily</option><option>As needed</option></select></label><button className="w-full mt-5 bg-slate-900 text-white rounded-lg py-3 text-sm font-semibold hover:bg-slate-700">Continue to assessment</button></form></div>}</div>;
}
